src/Entity/Configuracion.php
<?php

namespace App\Entity;

use App\Repository\ConfiguracionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConfiguracionRepository::class)
 */
class Configuracion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $precio_usuario;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrecioUsuario(): ?string
    {
        return $this->precio_usuario;
    }

    public function setPrecioUsuario(string $precio_usuario): self
    {
        $this->precio_usuario = $precio_usuario;

        return $this;
    }
}

src/Form/ConfiguracionType.php
<?php

namespace App\Form;

use App\Entity\Configuracion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConfiguracionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('precio_usuario', MoneyType::class, [
                'currency' => '',
                'attr' => [
                    'class' => 'form-control'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Configuracion::class,
        ]);
    }
}

src/Controller/ConfiguracionController.php
<?php

namespace App\Controller;

use App\Entity\Configuracion;
use App\Repository\ConfiguracionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ConfiguracionController extends AbstractController
{
    /**
     * @Route("admin/configuracion", name="configuracion")
     * @param ConfiguracionRepository $configuracionRepository
     * @param EntityManagerInterface $entityManager
     * @param Request $request
     * @return Response
     */
    public function index(ConfiguracionRepository $configuracionRepository, EntityManagerInterface $entityManager,
                          Request $request)
    {

        $config = $configuracionRepository->findOneBy([], ['id' => 'DESC']);

        if ($request->getMethod() === Request::METHOD_POST) {
            $precio = $request->request->get('precio_vendedor');
            $id = $request->request->get('id');
            if (empty($precio)) {
                $this->addFlash('error', 'Debe de ingresar un precio 🙁');
            } else {
                if (!empty($id)) {
                    $con = $configuracionRepository->find($id);
                    $con->setPrecioUsuario($precio);
                    $this->addFlash('success', 'Se actualizo correctamente 😃');
                } else {
                    $con = new Configuracion();
                    $con->setPrecioUsuario($precio);
                    $this->addFlash('success', 'Se inserto correctamente 😃');
                }
                $entityManager->persist($con);
                $entityManager->flush();
            }
        }

        return $this->render('configuracion/index.html.twig', [
            'config' => $config,
        ]);
    }
}

templates/configuracion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Configuracione Generales{% endblock %}

{% block body %}

    {% if config == null %}
        {% set id = 0 %}
        {% set precio_vendedor = 0 %}
    {% else %}
        {% set id = config.id %}
        {% set precio_vendedor = config.precioUsuario %}
    {% endif %}

    <!--titulo-->
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="float-right">
                    <a class="btn btn-primary" href="{{ path('admin_plan_nuevo') }}">
                        Nuevo Plan</a>
                </div>
                <h4 class="page-title">Configuraciones Generales</h4>
            </div>
        </div>
    </div> <!--end titulo-->
    <!-- Content -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="" method="post">
                        <input type="hidden" name="id" value="{{ id }}">
                        <div class="form-group row">
                            <label for="precio_vendedor" class="col-sm-3 col-form-label text-right">(*)Precio de cuentas
                                vendedor</label>
                            <div class="col-md-4">
                                <input type="text" value="{{ precio_vendedor }}" name="precio_vendedor"
                                       id="precio_vendedor"
                                       class="form-control">
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-9 ml-auto">
                                <button class="btn btn-success">Guardar</button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div> <!-- end Content -->
{% endblock %}