src/Entity/Cuenta.php
<?php

namespace App\Entity;

use App\Repository\CuentaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CuentaRepository::class)
 */
class Cuenta
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $password;

    /**
     * @ORM\ManyToOne(targetEntity=Plan::class, inversedBy="cuentas")
     */
    private $plan;

    /**
     * @ORM\Column(type="date")
     */
    private $created;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $vencimiento;

    /**
     * @ORM\OneToMany(targetEntity=DetalleCuenta::class, mappedBy="cuenta")
     */
    private $detalleCuentas;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="cuentas")
     */
    private $user;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $restante_cliente;

    /**
     * @ORM\Column(type="boolean")
     */
    private $estado;


    public function __construct()
    {
        $this->detalleCuentas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlan(): ?Plan
    {
        return $this->plan;
    }

    public function setPlan(?Plan $plan): self
    {
        $this->plan = $plan;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getVencimiento(): ?\DateTimeInterface
    {
        return $this->vencimiento;
    }

    public function setVencimiento(\DateTimeInterface $vencimiento): self
    {
        $this->vencimiento = $vencimiento;

        return $this;
    }

    /**
     * @return Collection|DetalleCuenta[]
     */
    public function getDetalleCuentas(): Collection
    {
        return $this->detalleCuentas;
    }

    public function addDetalleCuenta(DetalleCuenta $detalleCuenta): self
    {
        if (!$this->detalleCuentas->contains($detalleCuenta)) {
            $this->detalleCuentas[] = $detalleCuenta;
            $detalleCuenta->setCuenta($this);
        }

        return $this;
    }

    public function removeDetalleCuenta(DetalleCuenta $detalleCuenta): self
    {
        if ($this->detalleCuentas->contains($detalleCuenta)) {
            $this->detalleCuentas->removeElement($detalleCuenta);
            // set the owning side to null (unless already changed)
            if ($detalleCuenta->getCuenta() === $this) {
                $detalleCuenta->setCuenta(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getRestanteCliente()
    {
        return $this->restante_cliente;
    }

    /**
     * @param mixed $restante_cliente
     */
    public function setRestanteCliente($restante_cliente): void
    {
        $this->restante_cliente = $restante_cliente;
    }

    public function getEstado(): ?bool
    {
        return $this->estado;
    }

    public function setEstado(bool $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

}

src/Entity/Plan.php
<?php

namespace App\Entity;

use App\Repository\PlanRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PlanRepository::class)
 */
class Plan
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column (type="string", length=50)
     */
    private $nombre;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $precio;

    /**
     * @ORM\Column (type="integer")
     */
    private $numero_clientes;

    /**
     * @ORM\OneToMany(targetEntity=Cuenta::class, mappedBy="plan")
     */
    private $cuentas;

    public function __construct()
    {
        $this->cuentas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * @param mixed $nombre
     */
    public function setNombre($nombre): void
    {
        $this->nombre = $nombre;
    }

    /**
     * @return mixed
     */
    public function getPrecio()
    {
        return $this->precio;
    }

    /**
     * @param mixed $precio
     */
    public function setPrecio($precio): void
    {
        $this->precio = $precio;
    }

    /**
     * @return Collection|Cuenta[]
     */
    public function getCuentas(): Collection
    {
        return $this->cuentas;
    }

    public function addCuenta(Cuenta $cuenta): self
    {
        if (!$this->cuentas->contains($cuenta)) {
            $this->cuentas[] = $cuenta;
            $cuenta->setPlan($this);
        }

        return $this;
    }

    public function removeCuenta(Cuenta $cuenta): self
    {
        if ($this->cuentas->contains($cuenta)) {
            $this->cuentas->removeElement($cuenta);
            // set the owning side to null (unless already changed)
            if ($cuenta->getPlan() === $this) {
                $cuenta->setPlan(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getNumeroClientes()
    {
        return $this->numero_clientes;
    }

    /**
     * @param mixed $numero_clientes
     */
    public function setNumeroClientes($numero_clientes): void
    {
        $this->numero_clientes = $numero_clientes;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;


    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PerfilUsuario", mappedBy="user", cascade={"persist"})
     */
    private $perfil;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $saldo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Cliente", mappedBy="user")
     */
    private $clients;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Order", mappedBy="user")
     */
    private $orders;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="patrocinador", referencedColumnName="id", unique=false)
     */
    private $patrocinador;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Demo", mappedBy="user")
     */
    private $demo;

    /**
     * @ORM\OneToMany(targetEntity=Cuenta::class, mappedBy="user")
     */
    private $cuentas;

    /**
     * @ORM\OneToMany(targetEntity=Mensajes::class, mappedBy="user")
     * @Groups({"notificacion"})
     */
    private $mensajes;


    public function __construct()
    {
        $this->saldo = 0.00;
        $this->clients = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->cuentas = new ArrayCollection();
        $this->mensajes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     */
    public function setFirstName($firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName): void
    {
        $this->lastName = $lastName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $tem_rol = $this->roles;
        if (in_array('ROLE_USER', $tem_rol) == false) {
            $tem_rol[] = 'ROLE_USER';
        }
        return array_unique($tem_rol);
    }

    /**
     * @param array $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return mixed
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @param mixed $isActive
     */
    public function setIsActive($isActive): void
    {
        $this->isActive = $isActive;
    }

    /**
     * @return mixed
     */
    public function getPerfil()
    {
        return $this->perfil;
    }

    /**
     * @param PerfilUsuario $perfilUsuario
     */
    public function setPerfil(PerfilUsuario $perfilUsuario): void
    {
        $this->perfil = $perfilUsuario;
        $perfilUsuario->setUser($this);

    }

    /**
     * @return mixed
     */
    public function getSaldo()
    {
        return $this->saldo;
    }

    /**
     * @param mixed $saldo
     */
    public function setSaldo($saldo): void
    {
        $this->saldo = $saldo;
    }

    /**
     * @return mixed
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    /**
     * @return mixed
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    /**
     * @return mixed
     */
    public function getPatrocinador()
    {
        return $this->patrocinador;
    }

    /**
     * @param mixed $patrocinador
     */
    public function setPatrocinador($patrocinador): void
    {
        $this->patrocinador = $patrocinador;
    }

    /**
     * @return mixed
     */
    public function getDemo()
    {
        return $this->demo;
    }

    /**
     * @param mixed $demo
     */
    public function setDemo($demo): void
    {
        $this->demo = $demo;
    }

    /**
     * @return Collection|Cuenta[]
     */
    public function getCuentas(): Collection
    {
        return $this->cuentas;
    }

    public function addCuenta(Cuenta $cuenta): self
    {
        if (!$this->cuentas->contains($cuenta)) {
            $this->cuentas[] = $cuenta;
            $cuenta->setUser($this);
        }

        return $this;
    }

    public function removeCuenta(Cuenta $cuenta): self
    {
        if ($this->cuentas->contains($cuenta)) {
            $this->cuentas->removeElement($cuenta);
            // set the owning side to null (unless already changed)
            if ($cuenta->getUser() === $this) {
                $cuenta->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Mensajes[]
     */
    public function getMensajes(): Collection
    {
        return $this->mensajes;
    }

    public function addMensaje(Mensajes $mensaje): self
    {
        if (!$this->mensajes->contains($mensaje)) {
            $this->mensajes[] = $mensaje;
            $mensaje->setUser($this);
        }

        return $this;
    }

    public function removeMensaje(Mensajes $mensaje): self
    {
        if ($this->mensajes->contains($mensaje)) {
            $this->mensajes->removeElement($mensaje);
            // set the owning side to null (unless already changed)
            if ($mensaje->getUser() === $this) {
                $mensaje->setUser(null);
            }
        }

        return $this;
    }

}

src/Form/UserType.php
<?php


namespace App\Form;


use App\Entity\User;
use Symfony\Component\Form\Extension\Core\Type\BaseType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends BaseType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $user = new User();
        $builder
            ->add('roles', ChoiceType::class, [
                'multiple' => true,
                'expanded' => false,

                'choices' => [
                    'Revendedor' => 'ROLE_REVENDEDOR',
                    'Cliente' => 'ROLE_CLIENT',
                    'Administrador' => 'ROLE_ADMIN'
                ]
            ])
            ->add('email', EmailType::class)
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => [
                    'label' => 'Contraseña'
                ],
                'second_options' => [
                    'label' => 'Repita la contraseña'
                ]
            ])
            ->add('firstName', TextType::class, [
                'label' => 'Nombres',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('lastName', TextType::class, [
                'label' => 'Apellidos',
                'attr' => [
                    'class' => 'form-control'
                ]
            ])
            ->add('isActive', null, [
                'label' => 'Estado'
            ])
            ->add('perfil', PerfilUsuarioType::class);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class
        ]);
    }

}

templates/user/_form.html.twig
<form action="" method="post">
    <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label text-right">Email</label>
        <div class="col-sm-10">
            <input type="email" name="email" id="email" class="form-control">
        </div>
    </div>

    <div class="form-group row">
        <label for="password" class="col-sm-2 col-form-label text-right">Contraseña</label>
        <div class="col-sm-10">
            <input type="password" name="password" id="password" class="form-control">
        </div>
    </div>

    <div class="form-group row">
        <label for="repeatPassword" class="col-sm-2 col-form-label text-right">Repita la
            contraseña</label>
        <div class="col-sm-10">
            <input type="password" name="repeatPassword" id="repeatPassword" class="form-control">
        </div>
    </div>

    <div class="form-group row">
        <label for="roles" class="col-sm-2 col-form-label text-right">
            Asigne un rol</label>
        <div class="col-sm-10">
            <select name="roles" id="roles" multiple>
                <option value="ROLE_REVENDEDOR">Revendedor</option>
                <option value="ROLE_USER">Cliente</option>
                <option value="ROLE_ADMIN">Administrador</option>
            </select>
        </div>
    </div>
    <div class="form-group row">
        <label for="repeatPassword" class="col-sm-2 col-form-label text-right">Estado</label>
        <div class="col-sm-10">
            <label>
                <input type="checkbox" name="status" checked>
            </label>
        </div>
    </div>

    <hr>
    <p class="text-blue">Accesos demos: (No son obligatorios)</p>
    <div class="field_wrapper">
        <div class="form-group row">
            <label for="usuario" class="col-sm-2 col-form-label text-right">Usuario Demo</label>
            <div class="col-sm-10 mx-auto">
                <input id="usuario" type="text" name="usuario[]" value="" class="form-control">
                <a href="javascript:void(0);" class="add_button btn btn-info btn btn-sm" title="Add field">
                    <i class="typcn typcn-plus"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label for="password_demo" class="col-sm-2 col-form-label text-right">Password Demo</label>
        <div class="col-sm-10">
            <input type="text" id="password_demo" name="password_demo" class="form-control">
        </div>
    </div>


    <div class="form-group row">
        <div class="col-sm-10 ml-auto">
            <input type="submit" class="btn btn-success" value="{{ button_label|default('Guardar') }}">
        </div>
    </div>
</form>

<script src="{{ asset('js/jquery.js') }}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var maxField = 10;
        var addButton = $('.add_button');
        var wrapper = $('.field_wrapper');
        var fieldHTML = `
<div class="form-group row">
    <label for="usuario" class="col-sm-2 col-form-label text-right">Usuario Demo</label>
    <div class="col-sm-10">
        <input type="text" class="form-control" name="usuario[]" value=""/>
        <a href="javascript:void(0);" class="remove_button btn btn-danger btn-sm">
            <i class="typcn typcn-times"></i>
        </a>
    </div>
</div>`;
        var x = 1;

        $(addButton).click(function () {
            if (x < maxField) {
                x++;
                $(wrapper).append(fieldHTML);
            }
        });

        $(wrapper).on('click', '.remove_button', function (e) {
            e.preventDefault()
            $(this).parents('.form-group').remove();
            x--;
        });
    });
</script>

templates/user/perfil.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <h4 class="page-title">Bienvenido {{ user.firstName ~ ' ' ~ user.lastName }}</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ url('user_profile_edit') }}" class="btn btn-secondary btn-sm float-right">Editar</a>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>Nombres</th>
                            <td>{{ user.firstName }}</td>
                        </tr>
                        <tr>
                            <th>Apellidos</th>
                            <td>{{ user.lastName }}</td>
                        </tr>
                        <tr>
                            <th>E-mail</th>
                            <td>{{ user.email }}</td>
                        </tr>

                        {% if user.perfil %}
                            <tr>
                                <th>Foto</th>
                                <td>
                                    {% if user.perfil.foto %}
                                        <img class="img-thumbnail" width="50" height="50"
                                             src="{{ asset('uploads/perfil/') ~ user.perfil.foto }}" alt="">
                                    {% endif %}
                                </td>
                            </tr>

                            <tr>
                                <th>Whatsapp</th>
                                <td>{{ user.perfil.whatsapp }}</td>
                            </tr>
                            <tr>
                                <th>Dirección</th>
                                <td>{{ user.perfil.direccion }}</td>
                            </tr>
                            <tr>
                                <th>Pais</th>
                                <td>{{ user.perfil.pais }}</td>
                            </tr>
                            <tr>
                                <th>Facebook</th>
                                <td>{{ user.perfil.urlFacebook }}</td>
                            </tr>
                            <tr>
                                <th>Instagram</th>
                                <td>{{ user.perfil.urlInstagram }}</td>
                            </tr>

                            <tr>
                                <th>Youtube</th>
                                <td>{{ user.perfil.urlYoutube }}</td>
                            </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block title %}
    Mi perfil
{% endblock %}

templates/user/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario registrar{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="float-right">
                    <a href="{{ path('user_vendedor') }}">
                        <i style="font-size: 15px" class="typcn typcn-chevron-left"></i>
                        Regresar</a>
                </div>
                <h4 class="page-title">Crear usuario (Administrador - Vendedor - Cliente)</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    {% for message in app.session.flashBag.get('error') %}
                        <div class="alert alert-danger">
                            {{ message }}
                        </div>
                    {% endfor %}

                    {{ include('user/_form.html.twig') }}
                </div>
            </div>
        </div>
    </div>
    {{ usuarios }}
{% endblock %}

templates/user/vendedor_cuenta.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Ver cuentas
{% endblock %}
{% block body %}
    <!--titulo-->
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="float-right">
                    <a href="{{ path('app_vendedor') }}" class="btn btn-link">
                        <i style="font-size: 15px" class="typcn typcn-chevron-left"></i>
                        Regresar</a>
                    {#<a href="{{ path('app_vendedor_cuentas_nuevo', {'id': user.id}) }}"
                       class="btn btn-primary">Nuevo</a>#}
                </div>

                <h4 class="page-title">Cuentas de: {{ user.email }}</h4>
            </div>
        </div>
    </div> <!--end titulo-->
    {# {{ dump(cuentas) }} #}
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-bordered">
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Password</th>
                            <th>F. Creación</th>
                            <th>F. Vencimiento</th>
                            <th>Clientes Restantes</th>
                        </tr>
                        {% for key, c in cuentas %}
                            <tr class="{{ date(c.vencimiento) <= date() ? 'bg-soft-danger' : '' }}">
                                <td>{{ key + 1 }}</td>
                                <td>{{ c.username }}</td>
                                <td>{{ c.password }}</td>
                                <td>{{ c.created|date('d / m / Y') }}</td>
                                <td>{{ c.vencimiento|date('d / m / Y') }}</td>
                                <td>{{ c.restanteCliente }}</td>
                                {# <td>{{ c.vencimiento|date('d / m / Y') }}</td> #}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/vendedor_cuenta_nuevo.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    Registrar nueva cuenta
{% endblock %}
{% block body %}
    <!--titulo-->
    <div class="row">
        <div class="col-sm-12">
            <div class="page-title-box">
                <div class="float-right">
                    <a href="{{ path('app_vendedor_cuentas', {'id': user.id}) }}">
                        <i style="font-size: 15px" class="typcn typcn-chevron-left"></i>
                        Regresar</a>
                </div>
                <h4 class="page-title">Registrar nueva cuenta para: <span class="text-danger">{{ user.email }}</span>
                </h4>
            </div>
        </div>
    </div> <!--end titulo-->
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="precio">Costo de las cuentas: </label>
                                <input type="text" readonly class="form-control" value="{{ plan.precio }}">
                                <small class="form-text text-muted">Recuerda que si quieres cambiar el precio,
                                    puedes
                                    hacerlo desde las configuraciones generales <a
                                            href="{{ path('plan') }}">aquí</a>
                                </small>
                            </div>

                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="numero">Cantidad de clientes: </label>
                                <input type="text" readonly class="form-control" value="{{ plan.numeroClientes }}">
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="saldo">Saldo usuario: </label>
                                <input type="text" readonly class="form-control" value="{{ user.saldo }}">
                            </div>
                        </div>
                    </div>
                    {% if pass %}
                        <form action="" method="post">
                            <div class="form-group row">
                                <label for="username" class="col-sm-2 col-form-label text-right">
                                    * Usuario
                                </label>
                                <div class="col-md-6">
                                    <input type="text" id="username" name="username" class="form-control">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-sm-2 col-form-label text-right">
                                    * Contraseña
                                </label>
                                <div class="col-md-6">
                                    <input type="text" id="username" name="password" class="form-control">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-10 ml-auto">
                                    <button type="submit" class="btn btn-success">
                                        <i class="typcn typcn-location-arrow"></i>Guardar y Enviar
                                    </button>
                                </div>
                            </div>
                        </form>
                    {% else %}


                        <div class="alert alert-warning">
                            <i class="dripicons-warning px-1"></i>El usuario de esta cuenta no tiene saldo suficiente
                            para que le cree nuevas cuentas segun
                            su configuración, puede enviarle un mensaje pidiendo recargar la cuenta <a
                                    href="{{ path('app_message_nuevo', {'id': user.id}) }}">aquí</a>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
{% endblock %}